- name: Install required packages 
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - dirmngr
- name: Add clickhouse server to known hosts
  become: true
  known_hosts:
    name: "{{ hostvars[item].ansible_host }}"
    state: present
    key: "{{ lookup('pipe', 'ssh-keyscan {{ hostvars[item].ansible_host }}') }}"
    hash_host: true
  with_items: "{{ groups.clickhouse }}"  
- name: Add apt key from keyserver by id
  become: true
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80 
    id: 8919F6BD2B48D754
  tags: clickhouse
- name: Add official repo for clickhouse server and clickhouse client
  become: true
  lineinfile: 
    path: "/etc/apt/sources.list.d/clickhouse.list"
    line: "deb https://packages.clickhouse.com/deb stable main"
    create: true
  tags: clickhouse
- name: apt-get update
  become: true
  apt:  
    update_cache: yes
  tags: clickhouse
- name: Install clickhouse packages
  become: true
  apt:  
    name: "{{ clickhouse_packages }}"
  notify:
    - Fix ownership for folder  clickhouse 
    - Start clickhouse service 
  tags: clickhouse
- name: Flush handlers
  meta: flush_handlers
  tags: clickhouse
- name: Create database
  command: "clickhouse-client -q 'create database if not exists logs;'"
  register: create_db
  failed_when: create_db.rc != 0 and create_db.rc !=82
  changed_when: create_db.rc == 0
  tags: clickhouse